before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter pub run test_coverage
  - bash <(curl -s https://codecov.io/bash)
