name: abstract_flutter
description: A collection of abstract_dart structures for Flutter with Fields, Groups and Monoids.
version: 0.1.1
homepage: https://www.github.com/modulovalue/abstract_flutter
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
issue_tracker: https://github.com/modulovalue/abstract_flutter/issues

environment:
  sdk: '>=2.4.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.0
  abstract_dart: ^1.0.2

dev_dependencies:
  extra_pedantic: ^1.1.1+3
  flutter_test:
    sdk: flutter
